platform :ios, '8.0'
target "XZYS" do
pod 'MBProgressHUD', '~> 0.9.2'
pod 'BaiduMapKit', '~> 3.0.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'IQKeyboardManager', '~> 4.0.3'
pod 'Masonry', '~> 1.0.1'
pod 'MJRefresh', '~> 3.1.7'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJExtension', '~> 3.0.10'
pod 'pop', '~> 1.0.9'
pod 'UMengSocialCOM', '~> 5.2.1'

end